### ISSUE TITLE
[feature] Add models

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/django-freeradius#1]
- [x] add radius related models
- [x] add admin interface to manipulate database objects
- [x] add tests for basic features of models
- [x] add tests for basic features of admin (eg: open list page of each model)
- [x] ensure database structure works with [freeradius](http://freeradius.org/)

### Moved out of this issue

- ~~add references to the User model using `settings.AUTH_USER_MODEL` which should default to `auth.User`- see also https://docs.djangoproject.com/en/1.11/topics/auth/customizing/~~ Moved to #17
- ~~iterate to remove duplication of database fields when possible~~ Moved to #18

**Comment by lillopaco** [comment]
I opened a pull request for some items

**Comment by yakky** [comment]
@nemesisdesign how about moving the **User model** and denormalization tasks into separate issues? They looks big enough to deserve a dedicated tracking

**Comment by nemesisdesign** [comment]
@yakky sure, sorry for late delay

**Comment by yakky** [comment]
Closed via #13
