### ISSUE TITLE
[cleanup] Remove repetition of id declaration

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/django-freeradius#10]
these lines:

```
id = models.UUIDField(primary_key=True, db_column='id')
```

can be put in a shared abstract model which all the other models subclass.

**Comment by yakky** [comment]
@nemesisdesign this field is only used in models coming from OWUMS. I propose to avoid using UUID in models with many rows (like ``RadiusPostAuthentication``, ``RadiusAccounting``)
Actually for now I'd just keep them in OWUMS-related models and see how to handle them (especially with regards to moving to custom user models and denormalization)

**Comment by nemesisdesign** [comment]
@yakky for the short term is ok, regarding the long term we are aiming at a distributed setup but we'll need to think more carefully about this

**Comment by rohithasrk** [comment]
Create something like a `idMixin` or so, or shall we import https://github.com/openwisp/openwisp-utils/blob/master/openwisp_utils/base.py?

**Comment by nemesisdesign** [comment]
Closed as not relevant anymore.
