### ISSUE TITLE
[docs] Document API usage

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/django-freeradius#102]
Add an API page which explains briefly what each end point does, we can use `.. automethod::` and or `.. autofunction:: ` as we do in the [netjsonconfig docs](http://netjsonconfig.openwisp.org/en/stable/general/basics.html#implementation-details) to automatically include the docstrings of the views and link their source code.

Regarding the accounting API, we should very briefly describe how to use the new features just added in #101:
- pagination & header pagination
- filtering

**Comment by anurag-ks** [comment]
I'll take it up :+1:

**Comment by anurag-ks** [comment]
Since I added those features, let me finish it up :+1:

**Comment by anurag-ks** [comment]
@nemesisdesign I don't we can use .. automethod:: and or .. autofunction:: to document REST Api endpoints.
