### ISSUE TITLE
[tests] Are we really reusing base tests in the sample app?

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/django-freeradius#119]
Recently we worked on #83, but checking the tests in the sample app it doesn't seem to me that [the base tests are being imported](https://github.com/openwisp/django-freeradius/blob/1d2f7d8890d331ceb322d561c4a3e3649e6bb9ed/tests/sample_radius/tests.py) and hence I'm not sure the base tests are run in the sample app too.

**Comment by rohithasrk** [comment]
Yes. I've been wondering the same lately. These seem like some custom tests written for the SAMPLE_APP.

**Comment by nemesisdesign** [comment]
Let's try to fix this as last task of django-freeradius, it should be quick, if it's not quick we'll leave it open, what do you think @rohithasrk?

**Comment by rohithasrk** [comment]
Yeah @nemesisdesign. This good be a good first issue too for someone looking to contribute.
