### ISSUE TITLE
[API] Versioning

### ISSUE THREAD

**Issue by cappe87** [openwisp/django-freeradius#125]
It’s always a good idea to version API so we’ll add to the route /v1/

**Comment by nemesisdesign** [comment]
@rohithasrk https://github.com/openwisp/django-freeradius/blob/master/django_freeradius/urls.py#L7

The docs will need to be updated too: 
- https://github.com/openwisp/django-freeradius/blob/72760688959f993d059a74127eb170af064aa50e/docs/source/general/api.rst
- https://github.com/openwisp/django-freeradius/blob/72760688959f993d059a74127eb170af064aa50e/docs/source/general/freeradius.rst

**Comment by rohithasrk** [comment]
@nemesisdesign @cappe87 Is this version generally the app version?

**Comment by nemesisdesign** [comment]
@rohithasrk we should do this before releasing 0.1
