### ISSUE TITLE
Show the value field in admin panel on the attribute dropdown change

### ISSUE THREAD

**Issue by rohithasrk** [openwisp/django-freeradius#127]
As of now to add a radcheck instance from the admin panel we are having to do a double work as the value field isn't displayed in the add view. I think we'll need to display it.

**Comment by nemesisdesign** [comment]
Could you add some detail? I don't quite get it, maybe a screenshot would help.

**Comment by rohithasrk** [comment]
There is an attribute field but not a value field.

![screenshot from 2018-06-22 20-22-52](https://user-images.githubusercontent.com/13820931/41783270-1660d9ae-765a-11e8-8ef6-87262266be96.png)

**Comment by rohithasrk** [comment]
Also we need to address the issue #108 while closing #39

**Comment by 2stacks** [comment]
Is this related to #92?

**Comment by rohithasrk** [comment]
I woudn't say yes. But kind of you'll need to make some changes in the form fields itself.

**Comment by peppelinux** [comment]
It was already fixed here:
https://github.com/openwisp/django-freeradius/pull/93/files#diff-2e44be5f1a13a1864b4e90bda482b58cR14

https://github.com/openwisp/django-freeradius/pull/93

happy to see it fixed right now. Good job
