### ISSUE TITLE
[models] For fields other than the password types show the value in plain text, also while typing.

### ISSUE THREAD

**Issue by rohithasrk** [openwisp/django-freeradius#134]
When changing the RadiusCheck model instances from the admin interface, we see that the checks enforced on the password formats come in between adding any new non password attributes.

For ex., in #110 we are using attributes like Max-Session-Limit etc as attributes that are not password types. Support needs to be added for the same.

**Comment by 2stacks** [comment]
Same applies for help text.  I dont know if its worth implementing passwords and 'other' attributes separately but passwords obviously have unique requirements.  I think that since using radcheck for auth is an edge use case that more consideration should be given to non password attributes.

**Comment by rohithasrk** [comment]
Hey @2stacks yes. There is an improvement but I still think for attributes like Max-Session-Limit or so the admin interface still shows up the value in password format while typing. I think that can be changed using JS

**Comment by 2stacks** [comment]
Yeah I couldn't find a way to conditionally set the form widget in django.

**Comment by rohithasrk** [comment]
Hey @2stacks. We can use javascript for this. Shouldn't be tough.
