### ISSUE TITLE
[admin] Profile admin, show more useful data in list

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/django-freeradius#136]
In the profile admin, it would be nice to show:

- Daily session limit in hours (I believe the raw value is in seconds, a function is needed to calcualte this)
- Daily bandwidth limit in megabytes (I believe the raw value is in bytes, octets should mean bytes, a function is needed to calcualte this)
- Maximum all time session limit in hours (I believe the raw value is in seconds, a function is needed to calcualte this)
- created
- modified

@R9295 this could be another good thing for you to warm up, if you want, after #110 is merged

**Comment by R9295** [comment]
Will do after.

**Comment by nemesisdesign** [comment]
@R9295 can this be closed? Did you forget to add the close command in your PR?
