### ISSUE TITLE
[general] Configure isort / flake8 using setup.cfg

### ISSUE THREAD

**Issue by yakky** [openwisp/django-freeradius#14]
By using setup.cfg it's possible to configure flake8 / isort for more consistent results.

**Comment by yakky** [comment]
@nemesisdesign what do you think about moving flake8 / isort options to ``setup.cfg`` config file? See https://github.com/nephila/djangocms-blog/blob/develop/setup.cfg as and example

**Comment by nemesisdesign** [comment]
@yakky sure, it's much cleaner

**Comment by yakky** [comment]
@nemesisdesign I'll add to @lillopaco TODO :)

**Comment by yakky** [comment]
Fixed in #15
