### ISSUE TITLE
Make API reusable by adding base classes and inheriting from there

### ISSUE THREAD

**Issue by rohithasrk** [openwisp/django-freeradius#143]
As of now the API seems to be useful only in our classes. We need make them reusable so that users can customize accordingly. This would involve separation of the abstract logic and the app specific logic.

**Comment by nemesisdesign** [comment]
I don't understand very well what you mean

**Comment by nemesisdesign** [comment]
Ah ok now I understand, the API classes are not reusable. Why aren't the tests of the sample app failing?

**Comment by nemesisdesign** [comment]
The models are loaded via the swappable mechanism, that's why.
Anyway, :+1: for fully reusable views, including having the authorize view class based and more extensible.

**Comment by rohithasrk** [comment]
Yes @nemesisdesign. As of now, while developing #33 I'm making the authorize view class based. Would do it in the same PR.

**Comment by nemesisdesign** [comment]
@rohithasrk is this done or not? Please help me to clean up the issue list

**Comment by rohithasrk** [comment]
It works pretty well with openwisp-radius too

**Comment by nemesisdesign** [comment]
:+1:
