### ISSUE TITLE
Integrate django-freeradius as an openwisp module with multitenancy

### ISSUE THREAD

**Issue by rohithasrk** [openwisp/django-freeradius#151]
This thread aims to discuss the integration of django-freeradius into openwisp2. I'm developing a working prototype on my machine and pushing the code to https://github.com/rohithasrk/openwisp-radius-prototype.

Anyone interested could track it/ suggest features in this thread.

**Comment by nemesisdesign** [comment]
@rohithasrk keep us up to date

**Comment by rohithasrk** [comment]
Done with the basic extensibility. Working on adding the django-freeradius tests with openwisp-radius.
