### ISSUE TITLE
[API] Allow using API for authorization together with radius checks

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/django-freeradius#153]
It may be a good idea to allow the authorize API endpoint to return an empty response instead of a `AuthType: Reject`.

This way, as @2stacks suggested, freeradius would be able to perform other checks using other freeradius modules, for example radius checks, ldap, etc.

We just have to make sure that eventually the authorization request will fail if no freeradius module replies positively.

**Comment by 2stacks** [comment]
I'll test this as soon as I can.  The documentation I added will need to be
updated to reflect this change.

On Mon, Jul 30, 2018 at 11:04 AM, Federico Capoano <notifications@github.com

**Comment by nemesisdesign** [comment]
@2stacks noted down to update the docs, thanks
