### ISSUE TITLE
[models] Help text say "A unique ... name" but field is not unique

### ISSUE THREAD

**Issue by nemesifier** [openwisp/django-freeradius#167]
The `help_text` of `AbstractRadiusProfile.name` says `A unique profile name`, but the field has no `unique=True` constraint.

Same applies for `AbstractRadiusBatch`.

It would be useful to have them as unique fields, we just have to ensure that in multitenancy the constraint is removed in favour of `unique_together = ('organization', 'name')`, because different organizations may use the same name.

**Comment by atb00ker** [comment]
From what i have been able to understand, 
this shall be achieved in the following way, right?
```
# Main Abstract Class
class AbstractRadiusProfile(TimeStampedEditableModel):
  ...
  ...


# Concrete class 
class SomeConcreteSingleOrgRadiusProfile(AbstractRadiusProfile):
    name = models.CharField(unique=True)
  ...
  ...


# From what i have understood, multitenancy code is in a different repository and that 
# will simply inherit AbstractRadiusProfile and do something like this:

class SomeConcreteMultitenancyRadiusProfile(AbstractRadiusProfile, Multitenancy):
    name = models.CharField()
    
   class Meta:
      unique_together = ('organization', 'name')
  ...
  ...
```
