### ISSUE TITLE
[docs] Add management commands suggestion in installation page

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/django-freeradius#171]
**Reserved for GCI**

Some management commands are essential to make some features work (eg: deactivate and delete expired users).

We should recommend to add all the management commands in the crontab, they are all needed in a real world deployment. This should be done in the [setup page](https://django-freeradius.readthedocs.io/en/latest/general/setup.html).

**Comment by atb00ker** [comment]
The management commands seem to have their own [page](https://django-freeradius.readthedocs.io/en/latest/general/management_commands.html).

Shoud i add:
```
Note: Some management commands are necessary for enabling certain features and for database cleanup.
It recommended to have these commands in crontab in production environments.
[Find out more about these commands in its dedicated page](https://django-freeradius.readthedocs.io/en/latest/general/management_commands.html)
```
or should i add them in the same page separately.

**Comment by nemesisdesign** [comment]
@atb00ker yes that would be good, where would you add that text?
