### ISSUE TITLE
[models] Iterate to remove duplication of database fields when possible

### ISSUE THREAD

**Issue by yakky** [openwisp/django-freeradius#18]
General refactoring / normalization of existing models.
Consistency with freeradius standard tables must be taken into account

From #1

**Comment by rohithasrk** [comment]
Also, do you think there is a need to organizing the `base/models.py` more properly? I see managers, querysets, abstract-mixins all in one file. Could be a low priority thing though.

**Comment by nemesisdesign** [comment]
This issue is too vague.. I'm closing it. I will open more specific issues if I feel we need to improve something.
