### ISSUE TITLE
[models] Remove python_2_unicode_compatible decorators

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/django-freeradius#181]
**Reserved for GCI**

We dropped support for python 2.7, therefore we can remove all the `python_2_unicode_compatible` occurrences.

**Comment by traintraveler** [comment]
Can I take this up ?

**Comment by nemesisdesign** [comment]
Hey @traintraveler, Welcome!

Aare you a Google Code-In student? If yes, please wait the official start of the program in a few hours. If not, please don't, this task is reserved for Google Code-In participants.

**Comment by traintraveler** [comment]
@nemesisdesign No, I'm not a code-in student, cool.

**Comment by nemesisdesign** [comment]
@traintraveler if you want to contribute you can take a look at our [Contributor's Board](https://github.com/orgs/openwisp/projects/3), thank you!
