### ISSUE TITLE
[accounting API] Automatically determine groupname

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/django-freeradius#185]
**Reserved for GCI**

The radius accounting table has a `groupname` field which cannot be sent by freeradius in the accounting query, it has to be determined in another way.

There are different way to do this, but we should use the Django ORM so this feature can be handled automatically by the API. To implement this feature we should do the following:

- when saving a new accounting, the system can figure out the groupname related to the user by selecting the related `RadiusUserGroup` with the highest priority (`1` being highest)
- a few words describing this feature should be spent in the API documentation
- this feature can be turned off with a setting if needed, the setting must be documented in the available settings page and link the related API documentation section
- a test case which saves an accounting instance and expects the `groupname` to be filled automatically should be written
- a test case which saves an accounting via the API and expects the `groupname` to be filled automatically should also be written
- a test case which tests this feature when disabled should also be written, to implement how this is done you can take a look at `django_freeradius.tests.base.test_api.BaseTestApiReject`

**Comment by shashwat1002** [comment]
> a test case which saves an accounting instance and expects the groupname to be filled automatically should be written
@nemesisdesign , I wanted to know save how? The admin interface? 
I believe it won't be saving directly because we need to know the user to fill the group_name, so am I right in assuming that 

- 1 test case for saving from admin interface

-  1 test case for saving via api.

**Comment by nemesisdesign** [comment]
@shashwat1002 no no, this needs to happen via the accounting API, it's written in the text, but let me clarify in the title as well

**Comment by shashwat1002** [comment]
Means, I'll be writing two test cases? One with the setting enabled, the other without?
 (as opposed to three) and no changes to the admin site?
