### ISSUE TITLE
[QA] Increase test coverage to 100%

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/django-freeradius#186]
**Reserved for GCI**

After merging https://github.com/openwisp/django-freeradius/pull/184 and performing a big clean up the code coverage decreased.

Help us to to get it back to 100%.
To inspect the test coverage, run these commands:

```
coverage run --source=django_freeradius runtests.py
coverage html
```

The last command will create an HTML report which you can open in the browser and inspect in order to find which lines of codes need to be executed in the test to raise the test coverage.

Ask your mentors if you have any doubt.

**Comment by OltarzewskiK** [comment]
@nemesisdesign @R9295 Can I test models in `test_admin` file, because I found out that in `test_admin` I can do it with less amount of code or should I stick that `test_admin` is for `admin` and `test_models` is for `models`?
