### ISSUE TITLE
Updating Python versions in setup.py

### ISSUE THREAD

**Issue by kira0204** [openwisp/django-freeradius#187]
Hi,
As we are now supporting django 2.1(#166 ), we should drop the support for Python2.7 and also include Python3.5 and Python3.6 in the `setup.py`.
Thoughts?

**Comment by kira0204** [comment]
Hi,
I ran tests successfully with python 3.6, also I was talking about this https://github.com/openwisp/django-freeradius/blob/a45faaf80730c7263b799ac717da4a51f8d46446/setup.py#L62-L63

**Comment by nemesisdesign** [comment]
Sure I understood, you can proceed with the change!
