### ISSUE TITLE
[docs] Clarify django application must be running before starting freeradius

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/django-freeradius#223]
In the freeradius installation and configuration doc page it is not stated explicitly that the django application must be running before freeradius is started. This implicit assumption is throwing new users off track as shown by this post: https://groups.google.com/d/msg/openwisp/UvK23cJW_3k/1DCvk0EKDgAJ

We should add one or more notes regarding this, probably a note in the `debugging` section would also help.

**Comment by YashJipkate** [comment]
@nemesisdesign  I opened a PR in this regard.
