### ISSUE TITLE
[authentication] Add RadiusToken

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/django-freeradius#232]
The idea of creating a temporary token to use as a password in captive portals is very handy, but now we are using the rest framework Token model to perform the authorization in freeradius, but in order to completely separate the authentication of a user on the frontend apps that consume the openwisp API and the authorization of users in the wifi service, we should introduce a new `RadiusToken` model that will be dedicated to this purpose, tokens will be disposable: they are generated during authentication of the user and once they are used (in the freeradius authorize view) they are thrown away.

**Comment by Vivekrajput20** [comment]
Hi  Fed 
I have doubts regarding what we want to achieve here.
Currently we are using rest framework token model to authorize in freeradius and then the same token model is used in openwisp radius for the authentication. Now what we want to do is to keep using the rest framework token model for authorization in free radius and create a Radius token model that will inherit rest framework token model and use this model in the openwisp for authentication purpose.
Is that what we want?
Thanks 
Vivek

**Comment by nemesisdesign** [comment]
If there's an abstract model in DRF we can inherit from then yes, otherwise we can make a new one.
