### ISSUE TITLE
[pdf] Migrate to weasyprint

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/django-freeradius#243]
Migrate the html2pdf library to wasyprint, which is way to superior to what we are using now.

**Comment by anshuldutt21** [comment]
Hi, I would like to contribute to this issue.

**Comment by anshuldutt21** [comment]
I just encountered an issue while setting up the repository, there is no manage.py file in the code so do I need to manually create one for running the steps?

**Comment by 2stacks** [comment]
manage.py is in the /tests directory.  Are you following these steps https://django-freeradius.readthedocs.io/en/latest/general/setup.html#installing-for-development

**Comment by NoumbissiValere** [comment]
Hello,

The manage.py is in the tests directory.
So if you are standing in the project's root directory, to run manage.py
you could do something like python tests/manage.py

**Comment by anshuldutt21** [comment]
I ran the manage.py migrate command.  Lots of syntax errors are showing up in the filters.py file in the django-filters folder. After googling those errors I found out that they were due to the new version of django-filters 2.0 and downgrading it would maybe help but the older version of django-filters isnt compatible with the django-free radius version. Using python3  also isnt helping as environ is not importing. Can someone please help with this issue?

**Comment by atb00ker** [comment]
> I ran the manage.py migrate command. Lots of syntax errors are showing up in the filters.py file in the django-filters folder. After googling those errors I found out that they were due to the new version of django-filters 2.0 and downgrading it would maybe help but the older version of django-filters isnt compatible with the django-free radius version. Using python3 also isnt helping as environ is not importing. Can someone please help with this issue?

I think this is setup problem, can you please try to delete the repository and clone again and follow the steps in the README?
If the errors persist, please let us know. 
(Also, this is not related to the tasks, so please let talk about it on gitter or mailing list)

**Comment by anshuldutt21** [comment]
Ok. Actually I asked regarding it in gitter.They told me that I couldnt work on it since the issue is reserved for GCI.So,I switched over to another issue.

**Comment by atb00ker** [comment]
Okay! :smile:
