### ISSUE TITLE
Add freeradius-server-3.0.19 db fields

### ISSUE THREAD

**Issue by pythonwood** [openwisp/django-freeradius#244]
freeradius-server-3.0.19 db add feild framedinterfaceid, framedipv6address and so on now.

Is this project still devloping ?  will django model add feild soon?

**Comment by atb00ker** [comment]
The project is still under development.
However, since I don't know much about the fields you've mentioned, i'd defer for someone more experienced to comment on it. :smile:

**Comment by nemesisdesign** [comment]
@2stacks are there other fields we need to add?

At the moment I see these ones:

```
FramedIPv6Address
FramedIPv6Prefix
FramedInterfaceId
DelegatedIPv6Prefix
```

I don't see any other.

**Comment by 2stacks** [comment]
I didn't do a full comparison yet but you can see all available fields
here.
https://github.com/FreeRADIUS/freeradius-server/blob/master/raddb/mods-config/sql/main/postgresql/schema.sql
