### ISSUE TITLE
[requirements] Update dependencies & python version used.

### ISSUE THREAD

**Issue by atb00ker** [openwisp/django-freeradius#246]
We need to update all the dependencies.
We need to add support for django 3.0 and drop support for django versions that are older than 2.2.
We also need to test on python 3.6 and 3.7 on travis, dropping python 3.5.

Description edited by @nemesisdesign.

**Comment by adithyaanilkumar** [comment]
Hi  i am a beginner in contributing to open source projects. I would like  to work on this issue. Can you please help me with the same? i don't know where to start but i would love to work on this.

**Comment by atb00ker** [comment]
This issue is reserved for GCI right now! :smile: 
You may pick up any issue not related to GCI. :smile:
Here is our contributors board: https://github.com/orgs/openwisp/projects/3

**Comment by RohanJnr** [comment]
I am coming from GCI website.
Can I use pipenv ?

**Comment by atb00ker** [comment]
@RohanJnr For your own setup you can use anything you like, but please don't push `Pipfile` or any other pipenv residue! :smile:

**Comment by nemesisdesign** [comment]
This module does not support python 2, we can update the travis build to test using python 3.6 and python 3.7

**Comment by nemesisdesign** [comment]
And add django 3.0.
