### ISSUE TITLE
Add to create virtual environment in 'Installing for development' of documentation

### ISSUE THREAD

**Issue by TheOneAboveAllTitan** [openwisp/django-freeradius#248]
It might be possible that someone jumps directly over to 'Installing for development' topic without going through all steps. The first step in this topic should either be to create a virtual environment or reference to that step of the previous topic like 'After creating a virtual environment, do ...'

**Comment by okraits** [comment]
The first paragraph in the setup chapter is `Create a virtual environment`. So I don't really get the issue here.

**Comment by TheOneAboveAllTitan** [comment]
Yes, but that can be overlooked. A person who is eager for setting up development environment may not follow all the steps. Are they supposed to?

**Comment by 2stacks** [comment]
That sounds more like a personal problem as it's pretty standard practice
for python development.  I actually think that entire section should be
moved to the "Contributing" docs.  For what it's worth that section also
begins with "create a virtual environment".

**Comment by TheOneAboveAllTitan** [comment]
That is indeed a standard practice, and it felt odd that it was not mentioned in docs. 

> I actually think that entire section should be moved to the "Contributing" docs. 

This will be more helpful.

**Comment by okraits** [comment]
It _is_ mentioned in the docs. And it's also a standard practice for deployment, thus it makes sense that it's the first paragraph of the Setup chapter.
Even if you're looking for development instructions, you should have installed the package once before and read the docs from the beginning.
