### ISSUE TITLE
Only AbstractRadiusGroup.Meta has not db_table

### ISSUE THREAD

**Issue by pythonwood** [openwisp/django-freeradius#250]
https://github.com/openwisp/django-freeradius/blob/master/django_freeradius/base/models.py 
line 488:
`    class Meta:
        verbose_name = _('group')
        verbose_name_plural = _('groups')
        abstract = True`

**It cause:**
1. when django_freeradius in INSTALL_APPS ，create table django_freeradius_radiusgroup
1. when django_freeradius in INSTALL_APPS ，create table sample_radius_radiusgroup ( app in src tests/)

I modify django_freeradius app directly in the begining,  now I create a app like sample_radius to extends django_freeradius tables column so that I can keep django_freeradius upstream to master for future update.  
**I get error:**
`"Table 'freeradius.xxxapp_radiusgroup' doesn't exist")`

Temporaryly, I can deal it by add db_table=django_freeradius_radiusgroup.

**summery:** 
Is it necessary that AbstractRadiusGroup do not had db_table ?

**Comment by nemesisdesign** [comment]
I really do not understand this. I'm closing it since it doesn't seem a bug report.
If you have further questions please reply here or use the [support channels of OpenWISP](http://openwisp.org/support.html).
