### ISSUE TITLE
[docs] Improve installation documentation

### ISSUE THREAD

**Issue by atb00ker** [openwisp/django-freeradius#253]
Currently our installation for development documentation in django-freeradius has couple of errors.

For this task, you need to do the following
1. Follow documentation to install for development
2. Fix the error that you face during installation
The steps will be roughly:
2.1 If you are on debian 10 you may need to install: default-libmysqlclient-dev and libpq-dev
2.2 Run: `pip install -r requirements.txt -r requirements-test.txt` instead of `pip install -r requirements-test.txt`
2.3 Note if you face any other issue and let the mentors know about it.
3. Document the changes in the docs
3.1 You need to add 2.1 as a side note only for debian 10+ and ubuntu 19.04+ (example: look at the note: [here](https://django-freeradius.readthedocs.io/en/latest/general/setup.html#create-a-virtual-environment))
3.2 You need to add 2.2 as a troubleshooting point after installation
4. A lot of things are repeated for no good reason in "contributing" as well. See [here](https://django-freeradius.readthedocs.io/en/latest/general/contributing.html) remove this duplication).
5. Finally build changes as done [here](https://django-freeradius.readthedocs.io/en/latest/general/contributing.html#update-the-documentation) and make a pull request.

**Comment by 2stacks** [comment]
I can confirm that step 2.1 install `libpq-dev` is needed for Ubuntu 18.04 with newer kernel versions (5.x).

**Comment by oltarzewskik** [comment]
Starting working on it :+1:

**Comment by oltarzewskik** [comment]
> Run: pip install -r requirements.txt -r requirements-test.txt instead of pip install -r requirements-test.txt

why? `python setup.py develop` installs `requirements.txt` and `pip install -r requirements-test.txt` installs `requirements-test.txt`.

**Comment by atb00ker** [comment]
> @atb00ker why can not I simply follow docs?
python setup.py develop installs requirements.txt and pip install -r requirements-test.txt installs requirements-test.txt.

@oltarzewskik Go ahead, test if it works, I just have a habit of manually doing it so that's how I've written the steps! :smile:
