### ISSUE TITLE
[docs] contribution guildelines

### ISSUE THREAD

**Issue by atb00ker** [openwisp/django-freeradius#255]
The `django-freeradius` docs has it's own contribution page [here](https://django-freeradius.readthedocs.io/en/latest/general/contributing.html).
Which makes no mention of the contribution page of the organization [here](http://openwisp.io/docs/developer/contributing.html)

We want to mention the organization guidelines in the `django-freeradius` documentation and remove any duplicate documentation from the django-freeradius contribution page.

(Remember to read https://django-freeradius.readthedocs.io/en/latest/general/contributing.html#update-the-documentation)

**Comment by varadhbhatnagar** [comment]
I'll take up this task.
