### ISSUE TITLE
You're seeing this error because you have DEBUG = True in your Django settings file. Change that to False, and Django will display a standard 404 page

### ISSUE THREAD

**Issue by rallep71** [openwisp/django-freeradius#260]
You're seeing this error because you have DEBUG = True in your Django settings file. Change that to False, and Django will display a standard 404 page

I don't want to have to post the whole thing again, so I just link it

https://github.com/2stacks/freeradius-django/issues/13

**Comment by nemesisdesign** [comment]
Closing because invalid.
