### ISSUE TITLE
[docs] Add step to install Weasy Print

### ISSUE THREAD

**Issue by Vivekrajput20** [openwisp/django-freeradius#261]
You need to also install the GTK+ libraries (not just weasyprint), in order for weasyprint to render the final PDF.
You can find the installation instructions for your OS documented on[ weasyprint's website](https://weasyprint.readthedocs.io/en/stable/install.html#debian-ubuntu).
If these libraries are not installed, starting the server throws an error. Add a step to install libraries required for weasyprint in the installation guide.

**Comment by Vivekrajput20** [comment]
@nemesisdesign due to this issue, openwisp-radius is also affected and it also requires to install these libraries.

**Comment by atb00ker** [comment]
`docker-openwisp` was also affected, I had to install `cairo` & `pango`. :smile:
