### ISSUE TITLE
[API] How to limit usage?

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/django-freeradius#33]
What's the best and simplest way to limit who can use the API?

Initially I thought about allowing specific ip ranges but then I thought maybe using some sort of token authentication may be good too.

PS: we should choose a solution which is also simple to automate via ansible

**Comment by peppelinux** [comment]
https://github.com/Tivix/django-rest-auth

**Comment by rohithasrk** [comment]
@nemesisdesign Can we do something from the freeradius's end? Given that we are configuring the API from freeradius as well.

**Comment by anurag-ks** [comment]
DRF's token authentication combined with permissions for the class based API views ? @nemesisdesign

**Comment by rohithasrk** [comment]
@anurag-ks. Yep. That's something we can do from django's side. But I think freeradius has some features which could come to use here.
