### ISSUE TITLE
[tests] Make all the tests reusable  

### ISSUE THREAD

**Issue by lillopaco** [openwisp/django-freeradius#35]

**Comment by peppelinux** [comment]
Would we like to create a unit test method to take some arguments to introduce an generalized approach?

We could introduce a method as an interface that call some other private methods of the class.
Do we start with a GCI task?

**Comment by nemesisdesign** [comment]
@peppelinux we do this in other openwisp2 modules, take a look:

- https://github.com/netjson/django-netjsongraph/tree/master/django_netjsongraph/tests/base
- https://github.com/openwisp/django-loci/tree/master/django_loci/tests/base

Yes let's create it

**Comment by nemesisdesign** [comment]
Closed by 79a451c402fde45afdf5277f171ca33665c35830

See @R9295, we forgot to close this ticket because the commit message didn't close it automatically.
It's important to automate this stuff because it's such a waste of time to do it manually.

**Comment by R9295** [comment]
@nemesisdesign gotcha, will do next time.
