### ISSUE TITLE
[authorize] Allow to enforce session limits

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/django-freeradius#39]
We have to mainly 2 things:

- [ ] add a way (or establish what's the best way using the current available SQL tables) to define limits to the session of the users
- [ ] enforce these limits in the authorize API method

More specifically, we need to be able to replicate at least two features of [OpenWISP User Management System](https://github.com/openwisp/OpenWISP-User-Management-System):

- [ ] daily bandwidth counter
- [ ] daily session limit

We still need to understand in practice what's the best way to implement this feature.

**Comment by rohithasrk** [comment]
Working on this.
