### ISSUE TITLE
[feature] Batch "add users" feature

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/django-freeradius#4]
Implement a "batch add users" feature:

- each batch operation and its details must be saved to the database
- from each batch operation it must be possible to retrieve all the created username and password combinations
- deleting a batch operation should delete all the users created with it
- accounts created via batch operations may have an expiration date after which their account is no longer able to authenticate (this will probably require to introduce a few changes in the model)
- it would be very useful to add a way to generate a PDF with badges containing username and passwords generated in the batch operation - we can do a first basic version of this feature if we have time

**Comment by nemesisdesign** [comment]
@lillopaco I'm waiting from news on your side regarding this!

**Comment by cappe87** [comment]
I have all this features in an application wrote by me for the university
of Urbino. I don't know if my idea is the best idea (some people would say:
"It's somethings"). I'm avaiable to talk about this.

Il giorno dom 12 nov 2017 alle ore 11:54 Federico Capoano <
notifications@github.com> ha scritto:

**Comment by peppelinux** [comment]
I'm going to develop something similar based on a csv file import.
We could tag each csv file with a sha256 and take a log of all imported files (and entries id) in another schema (model).

Each istance of these log could be also exported as badge.

ps = ...I was developing just the CSV import/delete but the automatic export of badge is quite good for me too

**Comment by nemesisdesign** [comment]
@peppelinux, @lillopaco is working on this, Fiorella can you start pushing some code and open the pull request so other people can help us?

**Comment by peppelinux** [comment]
Ok I'll move to the next. If we need something to be developed before something else, well just write here, we could divide our tasks.

I've just finished flake and unisort revision on django-freeradius, I'm fixing coverage validation then I'll  ready for something else to do :)

**Comment by lillopaco** [comment]
@peppelinux  @nemesisdesign  Ok, sure!! Tonight I will start pushing code and open the pull request.

**Comment by peppelinux** [comment]
It would be great if it also be possible to:

- Choose the password type hash
- Choose to generate password using a multi-valued seeds fileds. Example value: "dog,23,_,!,W". The password could be generated with a wordlist generator algorithm (an example could be extracted here: https://github.com/peppelinux/gen2k/blob/master/Gen2k.py#276)
- Check if some accounts is duplicated (same_username@same_realm). Print it in a warning message or stop the import with an error message

**Comment by peppelinux** [comment]
Badge export: Would it be great to talk some Latex? :)
https://tex.stackexchange.com/questions/208142/print-a-receipt

**Comment by peppelinux** [comment]
Hi guys, is there some news on this feature?

**Comment by rohithasrk** [comment]
Made a prototype. Will push soon

**Comment by rohithasrk** [comment]
After discussion with @nemesisdesign the following things have been finalized for this feature.
1. CSV format would be: username password email firstname lastname
2. If CSV file contains all the fields then import them as they are, otherwise autogenerate the passwords leaving the other fields blank. (a method and tests for the same are needed)
3. The length of password should be customizable from settings.
4. CSV should contain the hash algorithm and should be used in production. (should discuss more on this)
5. Dedicated test files for this feature.
6. Add users by csv upload from admin interface.

**Comment by rohithasrk** [comment]
Regarding the batch-add-users feature for the events with a suffix for ex. GSoC and and 10 users to be generated, we could have users like GSoC1, GSoC2 ...  GSoC10 and random passwords generated. These can be stored in a PDF file and the PDF file could be stored in a file field and downloaded whenever necessary.
