### ISSUE TITLE
[Accounting] Add ForeignKey to settings.AUTH_MODEL

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/django-freeradius#42]
Add a `ForeignKey` from `RadiusAccounting` to `settings.AUTH_MODEL` which can be `NULL`.

We should add a mechanism through which the `ForeignKey` is automatically filled if the accounting is related to an user which is present in the database (if the user is not present in the database the foreign key will be left NULL, this is needed to support use cases which involve managing a freeradius proxy which forwards the authentication to different radius servers).

**Comment by peppelinux** [comment]
Probably django generic relations with an Admin custom form and a ModelManager that runs the game under the hood could be good for us

https://docs.djangoproject.com/en/2.0/ref/contrib/contenttypes/#generic-relations-in-admin

**Comment by nemesisdesign** [comment]
maybe we can drop this altogether and add a model method to retrieve the sessions of the user, not essential right now

**Comment by nemesisdesign** [comment]
I'm not sure this is a good idea anymore.
