### ISSUE TITLE
[docs] Document how to configure freeradius to work with django-freeradius

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/django-freeradius#5]
Document how to configure freeradius so that it can work with django-freeradius.

The documentation can be written in ReStructuredText format in the `README.rst` file present in this repository.

**Comment by nemesisdesign** [comment]
Done: https://github.com/openwisp/django-freeradius/commit/313e04ed7fd5d73f2cb8e80e1aad41e573fe51f6

We will have to update it as we add new features @lillopaco @yakky

**Comment by peppelinux** [comment]
Probably this issue should be reopenend, radiuscheck enhacements introduces new features that should be configured in radius check SELET SQL query in $FREERADIUS_CONF_PATH/mods-enabled/sql
