### ISSUE TITLE
[management] delete_old_radacct

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/django-freeradius#50]
In OpenWISP 1 we have implemented a few scripts that perform cleaning operations, we could implement these operation as management commands, eg:

- `./manage.py delete_old_radacct <numbe_of_days>` would delete sessions older than `<numbe_of_days>`

**Comment by peppelinux** [comment]
This is something I can do next week, if you agree

**Comment by nemesisdesign** [comment]
what about 2 GCI tasks? I know you can do this, but since it's so easy, it would be valuable to teach more people to contribute and maintain this project in order to enlarge the pool of maintainers

**Comment by peppelinux** [comment]
Ok

**Comment by nemesisdesign** [comment]
split the issue in 2 parts #73
