### ISSUE TITLE
[docs] development env uses sqlite but docs explain to use postgresql

### ISSUE THREAD

**Issue by AlessiaVe** [openwisp/django-freeradius#53]
When I installed django freeradius, I saw that some staps are missing in the documentation. I follow this tutorial, http://django-freeradius.readthedocs.io/en/latest/general/freeradius.html, for the installation of freeradius on a virtual machine with debian. Among installation requirements of sql there is also python_ mysql.db . After do that for the configuration with postgresql, It's necessary to install and import the schema.sql in postgres. There isn't any tutorial for this.

@nemesisdesign

**Comment by nemesisdesign** [comment]
You can create the database structure using `./manage.py migrate`. Did you import the sql from freeradius? That wouldn't work. Let me know. I'm asking this question in order to understand how to make the docs more explicit.

**Comment by AlessiaVe** [comment]
By default the enviroment for the development is sqlite but if someone wants make an installation for the production, the procedure is different and there isn't any description of this in the documentation (for example the passages which include the installation and configuration of postgres).

**Comment by peppelinux** [comment]
Mhhhh... If you agree I can produce a ansible-freeradius-sql
We talked about this with nemesis, He tolds me to do this after the stable release or something similar, in the sound of "don't you worry, there will come the time for this".

This could be driven according to this base configuration:
https://github.com/peppelinux/UniTools/blob/master/freeradius/freeradius_3.0.12_debian9.setup.sh

hint: comment line 138 and line 139 if you want to have the logs only into sql DB and not to /var/log/freeradius/radacct folder. The way I did it this way is to have a double, different, replica of the logs (paranoia)

**Comment by nemesisdesign** [comment]
Summary:

- the development environment uses sqlite by default
- in the [Installation and configuration of Freeradius 3](http://django-freeradius.readthedocs.io/en/latest/general/freeradius.html) page we show how to configure freeradius with postgres but we don't explain how to configure the development environment with postgresql

Proposed solution: add a new section after "How to install freeradius 3" in [Installation and configuration of Freeradius 3](http://django-freeradius.readthedocs.io/en/latest/general/freeradius.html) the page which explains how to reconfigure the development environment using postgresql, create the database and run the development server so freeradius will work when started.

This way we will achieve a smooth guide for newcomers.

**Comment by rohithasrk** [comment]
Can help with this.
