### ISSUE TITLE
Pypi package has empty module files.

### ISSUE THREAD

**Issue by daverickdunn** [openwisp/django-freeradius#57]
Hi guys,

It appears that the package on pypi has at least one empty module (my colleague reckons there were some others as well):

i.e. `lib/python3.5/site-packages/django_freeradius/urls.py` is just a blank file.

Importing it into Django, as per the basic instructions, results in the error:
```
django.core.exceptions.ImproperlyConfigured: 
The included URLconf  '<module 'django_freeradius.urls' from '/home/richard/.virtualenvs/panos-rest/lib/python3.5/site-packages/django_freeradius/urls.py'>' does not appear to have any patterns in it. 
If you see valid patterns in the file then the issue is probably caused by a circular import.
```

Installing the package from `https://github.com/openwisp/django-freeradius/tarball/master` however, everything works as expected and results in the module having the expected lines:

```
from django.conf.urls import include, url

from .api import urls as api

urlpatterns = [
    url(r'^api/', include(api)),
]
```

**Comment by nemesisdesign** [comment]
the package on pypi is just a placeholder in alpha stage that I issued to reserve the name, use the github tarball until we reach something that is good enough to be 0.1 release. A couple of important features are still missing from our roadmap.
