### ISSUE TITLE
[Feature] List of nas type in the nas add page

### ISSUE THREAD

**Issue by cappe87** [openwisp/django-freeradius#59]
In the nas add page we can add a list of nas type on the right of the input box.
A free input box will remain, user can decide to write a nas type or choose one from the list.
I think it would be help.
What do you think @nemesisdesign ?

**Comment by peppelinux** [comment]
These could be extracted by service-type from rfc 2865 and putted in tha app_settings as done for the hash type

https://www.iana.org/assignments/radius-types/radius-types.xhtml#radius-types-13

**Comment by cappe87** [comment]
This should be fixed by https://github.com/AlessiaVe/django-freeradius/commit/12e0539fbba5e61e3c485b2fa850396fe63f152f
![add nas django site admin](https://user-images.githubusercontent.com/6532945/33935199-609fb92c-dffb-11e7-8a60-989540616849.png)

**Comment by peppelinux** [comment]
Wonderfull, she just have to test flake/isort/coverage and then do a pull request !!!
