### ISSUE TITLE
[Feature] RadiusCheck should prevents duplicates entries by username

### ISSUE THREAD

**Issue by peppelinux** [openwisp/django-freeradius#65]
This feature should drop out the duplicate admin filter I done but... Yes it should.
We could improve AbstractRadiusCheckManager adding a check into create() overridden method.

If freeradius have duplicate username it will authenticate the session according to the oldest account.
The last inserted, with different password value, will be ignored.

This could also introduce a workaround into radiucheck query in freeradius sql dialect file but I think that it could be better avoid the creation on duplicates if you agree with me.

**Comment by cappe87** [comment]
I agree with your solution, but what do you think about realms? Do you use realms in your production environment?

**Comment by peppelinux** [comment]
Yes, we use only realms.
It works because every account have its own realm coded into its username value, probably I missed something or I probably did not understand the question correctly, if something missed just tell me more, I'll follow you in it.

**Comment by cappe87** [comment]
Sorry, in which table do you save realms? Do you allow two or more users with the same username but with different realms?

**Comment by peppelinux** [comment]
Freeradius stripes usernames into a realm according to a byte value like "@" coded into the account username. The same as the email, so default value is @ but it could also be changed in freeradius configuration.

According to this approach the realms for every account is coded into the username, this way:

peppelinux@guest.realm.it
peppelinux@dipartimento.realm.it

This way we could also have an unstriped account like "peppelinux" that not belongs to any realms, and the others with realm encoded into them.

I know that this approach is quite rough but radcheck works this way and we are too old to rock'n'roll and too young to die. Freeradius sounds a little bit patchy to me but works, still works :))

**Comment by peppelinux** [comment]
cappe87 I thought about the way you suggested to me, with your question. I realized that we could extends RadiusCheckAdmin[Form too] in a way to manage realms more like an ordinary group management, just a signal or a overridden method to split the realm from the account, get the realm from our management realm schema/model, append the realm to the splitted[0] account before saving it.

this could permit to us to manage realm like groups and move users from a realm to another via a AdminBackend action over thousand of accounts, leaving the legacy freeradius approach in a lower level of management without producing conflicts with this.

How this sounds to you?

**Comment by peppelinux** [comment]
...By the way, the more simple way to prevent duplicate entries by their username is adding a unique=True attribute in the model.Charfield of base.AbstractRadiusCheck.username

isn't it? :)

**Comment by rohithasrk** [comment]
@peppelinux I think the drawback here when you want to put more than one restriction on an username, we would want to use multiple radcheck instances. Like the way we are implementing the session limits feature. If done what you said, our app wouldn't allow to do so.

**Comment by peppelinux** [comment]
In my production environment I configured username as unique index. I said all the words, nothing more to say. Close it as it is
