### ISSUE TITLE
[Feature] Radius group users: radcheck m2m autocomplete

### ISSUE THREAD

**Issue by peppelinux** [openwisp/django-freeradius#66]
In RadiusGroupUsersAdmin We also need a "search and autocomplete" widget on m2m radiuscheck entries. Actually a user should scroll by hand and then select the desidered accounts holding CTRL key, this is not so easy for thousands of accounts :)

According to this I'm proposing to introduce this dependency in django-freeradius
django-autocomplete-light

I already developed using it in Django Admin backed, this should not be a problem for me.
Let me know if it sounds useful to you too :)

**Comment by anurag-ks** [comment]
Can I work on this ?

**Comment by nemesisdesign** [comment]
Development has moved to [openwisp-radius](https://github.com/openwisp/django-freeradius), this repository is going to be archived.
