### ISSUE TITLE
[Accounting API] Accounting start fails with coova-chilli

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/django-freeradius#69]
Coova chilli sends an accounting start request which doesn't include the following fields:

- `output_octets`
- `input_octets`
- `session_time`

We should allow these fields to be missing if the request is of type start and default to `0`.

**Comment by peppelinux** [comment]
Some references here:
https://coova.github.io/CoovaChilli/chilli-radius(5).html
https://github.com/coova/coova-chilli/blob/master/doc/attributes

**Comment by nemesisdesign** [comment]
So it turns out the request contains the fields but they are empty, eg:

```javascript
{
    "status_type": "Start",
    "session_id": "5a4f59aa00000001",
    "unique_id": "d11a8069e261040d8b01b9135bdb8dc9",
    "username": "username",
    "realm": "",
    "nas_ip_address": "192.168.182.1",
    "nas_port_id": "1",
    "nas_port_type": "Wireless-802.11",
    "session_time": "",
    "authentication": "",
    "input_octets": "",
    "output_octets": "",
    "called_station_id": "C0-4A-00-EE-D1-0D",
    "calling_station_id": "A4-02-B9-D3-FD-29",
    "terminate_cause": "",
    "service_type": "",
    "framed_protocol": "",
    "framed_ip_address": "192.168.182.3"
}
```

**Comment by nemesisdesign** [comment]
PS: interim-updates and accounting stop work though, which is good.
