### ISSUE TITLE
[docs] No file "sql" of freeradius-server

### ISSUE THREAD

**Issue by h0n3yc4k3** [openwisp/django-freeradius#75]
I have ubuntu 16.04.3 with last updates
I installed freeradius from site and repository (on first VM from sources and second from repository)
And there no directory *mods-available* (so there no with file *sql*)
But I found a very similar file called *sql.conf* except `dialect` value (there no this parametr)
![2017-12-25_162633](https://user-images.githubusercontent.com/34004367/34340196-7afe7896-e990-11e7-8094-fecff2cd0471.jpg)
What is wrong or its update of freeradius and we shoud update documentation?

**Comment by h0n3yc4k3** [comment]
Google says that it possible bcs I have Ubuntu 16.04
It shoud be fixed on Ubuntu 17.04

**Comment by EdoPut** [comment]
Hello and thanks for this report.

Please do not use pictures, you can paste the file so that everyone can read it without problem.
Have you followed some instructions? Did you have any trouble with any steps?

You can use markdown to format your message. I for example like to paste file content with a **code formatting**

```ini
#This is my configuration file
foo = 1
bar = 2
```

You can read more about formatting your text [here](https://guides.github.com/features/mastering-markdown/)

Merry Christmas

**Comment by h0n3yc4k3** [comment]
The reason was that I used ubuntu 16.04 (exactly 16.04.03 with last updates)
With ubuntu 17.04 (I updated too) all look ok
I thought that last updates will be enough

**Comment by nemesisdesign** [comment]
Right, the modules need to be enabled, #74 seem to address this issue

**Comment by EdoPut** [comment]
@h0n3yc4k3 you are right, the docs page does not mention the correct path for your system.

As you are using [16.04 (AKA Xenial)][releases] we must refer to a different file, would you like to add this information to the [documentation page][freeradius]?

You can edit this https://github.com/openwisp/django-freeradius/blob/master/docs/source/general/freeradius.rst and make a pull request so we can improve.

To resolve your issue we should see the content of those files and try to validate them.

As you are using systemd we should look at the logs using the command `journalctl -b 0 -u freeradius`, please paste those here. 
 
[freeradius]: http://django-freeradius.readthedocs.io/en/latest/general/freeradius.html#how-to-install-freeradius-3
[releases]: https://wiki.ubuntu.com/Releases

**Comment by h0n3yc4k3** [comment]
@EdoPut there no `freeradius-rest` package and path on Ubuntu 16.04 is */etc/freeradius/sites-available*
Very similar file is */etc/freeradius/sql.conf*, but there no *dialect* parametr (it contains all another)
Content of */etc/freeradius/sql.conf* file: https://pastebin.com/CZhqtXUc
Log of command 'journalctl -b 0 -u freeradius` very long, there last lines: https://pastebin.com/wxs1BPBU

**Comment by EdoPut** [comment]
> there no freeradius-rest package

You mean you can't install the `freeradius-rest` package? This means that you won't be able to use django-freeradius from freeradius. There are two solutions, upgrade to ubuntu 17.04 or add the repository `ppa:freeradius/stable-3.0`

Have you run the command?

```sh
apt-add-repository ppa:freeradius/stable-3.0
apt-get update
```

Can you search for the package `freeradius-rest` with `apt-cache search freeradius-rest`?

> path on Ubuntu 16.04 is /etc/freeradius/sites-available

This is not a problem if freeradius knows where to find it, as I said previously you can improve the documentation page to report it. This would be a good first contribution that I would welcome.

> Very similar file is /etc/freeradius/sql.conf, but there no dialect parametr (it contains all another)

This is not a problem if you are not using the sql provider, do you want to use it?

From the logs you pasted the configuration seems good so the problem could be that freeradius can't communicate with the database or rest provider and returns this error.

```
Dec 26 04:05:04 ubuntu freeradius[103237]: Configuration appears to be OK
Dec 26 04:05:04 ubuntu freeradius[103237]: rlm_rest (rest): Removing connection pool
Dec 26 04:05:04 ubuntu freeradius[103237]: rlm_sql (sql): Removing connection pool
Dec 26 04:05:04 ubuntu systemd[1]: freeradius.service: Control process exited, code=exited status=1
Dec 26 04:05:04 ubuntu systemd[1]: Failed to start FreeRADIUS multi-protocol policy server.
Dec 26 04:05:04 ubuntu systemd[1]: freeradius.service: Unit entered failed state.
Dec 26 04:05:04 ubuntu systemd[1]: freeradius.service: Failed with result 'exit-code'.
```

**Comment by peppelinux** [comment]
Hi @h0n3yc4k3, when we get some dirty in the configuration files, in way that is difficult to figure how where the problem is, remember to run freeradius in debug mode:
````
freeradius -XXX
````
In the last years I produced a procedure to configure a Freeradius server following a common profile.
The resource is: 

https://github.com/peppelinux/UniTools/blob/master/freeradius/freeradius_3.0.12_debian9.setup.sh

following you pastebin log I can tell that you loaded the dummy sal driver:

````
Dec 26 04:04:48 ubuntu freeradius[103210]: rlm_sql (sql): Driver rlm_sql_null (module rlm_sql_null) loaded and linked
````

So You have to deal with it, try this:

````
sed -i 's/.*driver = "rlm_sql_null"/driver = "rlm_sql_mysql"/' $RADCONFD/mods-available/sql

````

**Comment by h0n3yc4k3** [comment]
@EdoPut yes. When I try install it with `apt-add-repository ppa:freeradius/stable-3.0` Im getting error: https://pastebin.com/4GpMj3YH
Yes, I already updated to Ubuntu 17.04


> Can you search for the package
Yes, there no results ;(

Ok, I will try to check it

**Comment by h0n3yc4k3** [comment]
@peppelinux I think you as @EdoPut are right

Tue Dec 26 05:37:34 2017 : Info: rlm_rest (rest): Opening additional connection (0), 1 of 32 pending slots used
Tue Dec 26 05:37:34 2017 : Debug: rlm_rest (rest): Connecting to "http://127.0.0.1/"
Tue Dec 26 05:37:34 2017 : Error: rlm_rest (rest): Connection failed: 7 - Couldn't connect to server
Tue Dec 26 05:37:34 2017 : Error: rlm_rest (rest): Opening connection failed (0)
Tue Dec 26 05:37:34 2017 : Debug: rlm_rest (rest): Removing connection pool
Tue Dec 26 05:37:34 2017 : Error: /etc/freeradius/3.0/mods-enabled/rest[1]: Instantiation failed for module "rest"

I'll try to deal with it

**Comment by EdoPut** [comment]
> I already updated to Ubuntu 17.04

Then remove the `freeradius` package with all its documentation with

```
apt-get purge freeradius
```

Then we can purge and remove the ppa as it is not necessary for 17.04

```
sudo add-apt-repository --remove ppa:freeradius/stable-3.0
```

Finishing with updating the local repository index and installing `freeradius` again

```
apt-get install freeradius freeradius-rest
```

**Comment by h0n3yc4k3** [comment]
Yes, I did it. Left to configure freeradius 😌

**Comment by EdoPut** [comment]
Wonderful, keep going!
