### ISSUE TITLE
[bug][RadiusCheckAdmin] RadiusCheck new entries doesn't show value password field

### ISSUE THREAD

**Issue by peppelinux** [openwisp/django-freeradius#92]
RadiusCheck new entries doesn't show value password field, actually this must be done after its creation, in modify page.

**Comment by peppelinux** [comment]
fixed in
https://github.com/openwisp/django-freeradius/pull/93

**Comment by nemesisdesign** [comment]
@2stacks can this be closed?

**Comment by nemesisdesign** [comment]
no problem @2stacks, thanks for letting me know
