### ISSUE TITLE
Add support to django > 2.0 in requirements-test

### ISSUE THREAD

**Issue by rohithasrk** [openwisp/django-freeradius#94]

**Comment by HargovindArora** [comment]
@rohithasrk can you guide me on how to proceed with this issue? :)

**Comment by rohithasrk** [comment]
Hi @HargovindArora. The best way would be to setup the environment with Django > 2.0 and runtests until all of them pass. Also, you can check out the Django changelogs and the PRs which reference the same. https://github.com/netjson/django-netjsongraph/commit/c6b367f295964a2ed081b6691cc3cc2a3e293dd1 for example.

**Comment by HargovindArora** [comment]
Thanks, @rohithasrk . I'm on this!
