### ISSUE TITLE
Add openwisp admin theme to django-freeradius

### ISSUE THREAD

**Issue by rohithasrk** [openwisp/django-freeradius#96]
Refer to https://github.com/openwisp/openwisp-utils and add the uniform admin theme of openwisp to this project as well.

**Comment by nemesisdesign** [comment]
We should add the theme only in the test environment, eg: `test/settings.py` because other users/developers may want to use the app without the theme.

**Comment by anurag-ks** [comment]
Can I work on this ?

**Comment by rohithasrk** [comment]
Hey @anurag-ks. That would be great :D

**Comment by anurag-ks** [comment]
@rohithasrk is this the fix that you guys wanted - https://github.com/openwisp/django-freeradius/pull/98
