### ISSUE TITLE
Import shared code from openwisp-utils

### ISSUE THREAD

**Issue by rohithasrk** [openwisp/django-freeradius#97]
Refer to [openwisp-utils](https://github.com/openwisp/openwisp-utils) and import the code which is being duplicated here from there.

**Comment by nemesisdesign** [comment]
@rohithasrk stated as it's now this issue is not helpful to new contributors, they would have to read the entire code of both openwisp-utils and django-freeradius which is just not gonna happen.

**Comment by rohithasrk** [comment]
I think there is only one Abstract model that we are using, i.e., `TimeStampedEditableModel`.

**Comment by anurag-ks** [comment]
I have made the changes, will push the code soon.
