### ISSUE TITLE
[Accounting-API] Improve filtering

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/django-freeradius#99]
Allow filtering for these fields:

- `username` filter for a specific username
- `called_station_id`
- `calling_station_id`
- `start_time`: look for sessions started in a specific date (in `YYYY-MM-DD` format)
- `stop_time`: look for sessions finished in a specific date (in `YYYY-MM-DD` format)
- `open`: this is not a database field but a boolean filter that looks for sessions which have `stop_time == None`

I suggest to use this kind of implementation: http://www.django-rest-framework.org/api-guide/filtering/#djangofilterbackend

**Comment by anurag-ks** [comment]
@nemesisdesign for `start_time` and `stop_time` will ISO 8601 format work ?

**Comment by anurag-ks** [comment]
https://github.com/openwisp/django-freeradius/pull/101 fixed @nemesisdesign
